image: alpine:3.13.5

stages:
- deploy

variables:
  GITLAB_HOST: 'https://git.twogether.io'

before_script:
- apk add --no-cache curl

deploy_tag:
  stage: deploy
  script:
  - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  rules:
  - if: '$CI_COMMIT_TAG'

deploy_branch:
  stage: deploy
  script:
  - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=$CI_COMMIT_BRANCH "$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  rules:
  - if: '$CI_COMMIT_BRANCH'

