language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

script:
    - vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 -p src/
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
