services:
    PartnerMarketing\FileSystemBundle\Factory\FileSystemFactory:
        class: PartnerMarketing\FileSystemBundle\Factory\FileSystemFactory
        arguments:
            - "%partner_marketing_file_system.default_file_system%"
            - "%partner_marketing_file_system.config%"
            - "%partner_marketing_file_system.tmp_dir%"
