services:
    partnermarketing_file_system.factory:
        class: "Partnermarketing\\FileSystemBundle\\Factory\\FileSystemFactory"
        arguments:
            - "%partnermarketing_file_system.default_file_system%"
            - "%partnermarketing_file_system.config%"
            - "%partnermarketing_file_system.tmp_dir%"
